

StructureTypes = {

}

Structures = {
    ["no_building"] = {},
    ["alien_control_center"] = {},
    ["armor_barracks"] = {},
    ["artemis_system_net"] = {},
    ["astro_university"] = {},
    ["atmosphere_renewer"] = {},
    ["autolab"] = {},
    ["automated_factory"] = {},
    ["battlestation"] = {},
    ["capitol"] = {},
    ["cloning_center"] = {},
    ["colony_base"] = {},
    ["deep_core_mine"] = {},
    ["core_waste_dump"] = {},
    ["dimensional_portal"] = {},
    ["biospheres"] = {},
    ["food_replicators"] = {},
    ["gaia_transformation"] = {},
    ["currency_exchange"] = {},
    ["galactic_cybernet"] = {},
    ["holo_simulator"] = {},
    ["hydroponic_farm"] = {},
    ["marine_barracks"] = {},
    ["barrier_shield"] = {},
    ["flux_shield"] = {},
    ["gravity_generator"] = {},
    ["missile_base"] = {},
    ["ground_batteries"] = {},
    ["radiation_shield"] = {},
    ["stock_exchange"] = {},
    ["supercomputer"] = {},
    ["pleasure_dome"] = {},
    ["pollution_processor"] = {},
    ["recyclotron"] = {},
    ["robotic_factory"] = {},
    ["research_lab"] = {},
    ["robo_miner_plant"] = {},
    ["soil_enrichment"] = {},
    ["space_academy"] = {},
    ["spaceport"] = {},
    ["star_base"] = {},
    ["star_fortress"] = {},
    ["stellar_converter"] = {},
    ["subterranean_farms"] = {},
    ["terraforming"] = {},
    ["warp_interdictor"] = {},
    ["weather_controller"] = {},
    ["fighter_garrison"] = {},
    ["artificial_planet"] = {},
}